_pipeline:
  _relax_polygpu:
    atomtypes: not used
    cool_time: 1000000
    elastic_mod: 83
    end_temp: 0.1
    heat_time: 1000000
    infile: Ag_10nm.lmp
    init_temp: 0.1
    outfile: Ag_10nm_gpurelax.lmp
    potential: UNEP_v1.txt
    relax_time: 10000000
    start_temp: 700
    stop_temp: 700
  create_monocrystal:
    a: 4.08
    atomtypes: false
    c: 0
    outfile: fcc.xsf
    type: fcc
  create_polycrystal:
    grain_num: 10
    outfile: Ag_10nm.lmp
    stamp_file: fcc.xsf
    x: 100
    y: 100
    z: 100
cores: 20
pipeline:
- _create_monocrystal:
    a: 4.08
    atomtypes: false
    c: 0
    outfile: fcc.xsf
    type: fcc
- _create_polycrystal:
    grain_num: 10
    outfile: Ag_10nm.lmp
    stamp_file: fcc.xsf
    x: 150
    y: 150
    z: 150
- _convert_format_atomsk:
    infile: Ag_10nm.lmp
    outfile: Ag_10nm.xyz
- _minimize_polygpu:
    atomtypes: not used
    energy_file: pureE
    infile: Ag_10nm.lmp
    intype: lammps-data
    minimize_vol: true
    outfile: Ag_10nm_min.xyz
    potential: Unep_v1.txt
    tmp_name: tmp_dir
- _make_orthogonal:
    infile: Ag_10nm_min.xyz
- _relax_polygpu:
    atomtypes: not used
    cool_time: 100000
    elastic_mod: 76
    end_temp: 0.1
    heat_time: 100000
    infile: Ag_10nm_min.xyz
    init_temp: 0.1
    intype: extxyz
    outfile: Ag_10nm_relax.xyz
    potential: Unep_v1.txt
    relax_time: 1000000
    start_temp: 700
    stop_temp: 700
    tmp_name: tmp_dir
- _minimize_polygpu:
    atomtypes: not used
    energy_file: pureE
    infile: Ag_10nm_relax.xyz
    intype: extxyz
    minimize_vol: true
    outfile: Ag_10nm_min2.xyz
    potential: Unep_v1.txt
    tmp_name: tmp_dir
- _make_orthogonal:
    infile: Ag_10nm_min2.xyz
- _convert_format_atomsk:
    infile: Ag_10nm_min2.xyz
    outfile: Ag_10nm_min2.lmp
- _get_gb_ids:
    cutoff: 3.5
    infile: Ag_10nm_min2.lmp
    outfile: GBs.lst
- _soap:
    atomtypes: false
    cores: false
    infile: Ag_10nm_min2.lmp
    l_max: 12
    n_max: 12
    outfile: soap.lst
    sigma: 1
    soap_cutoff: 6.0
- _extract_pca:
    infile: soap.lst
    outfile: pca.lst
    pca_num: 10
- _select_points:
    gb_file: GBs.lst
    infile: pca.lst
    outfile: GBs_best.lst
    points_num: 300
    random_state: 420
- calculate_spectra:
    atomtypes: false
    base_energy: pureE
    gb_file: GBs_best.lst
    infile: Ag_10nm_min2.lmp
    minimize_args:
      energy_file: E
      intype: lammps-data
      tmp_name: tmp_dir
    minimize_func: minimize_polygpu
    outfile: Eseg_best_calc
    potential: Unep_v1.txt
- calculate_spectra:
    atomtypes: false
    base_energy: nullE
    gb_file: Bulk_ids.lst
    infile: Ag_10nm_min2.lmp
    minimize_args:
      energy_file: E
      intype: lammps-data
      tmp_name: tmp_dir
    minimize_func: minimize_polygpu
    outfile: Enull_calc
    potential: Unep_v1.txt
- move_spectra:
    outfile: Eseg_best_moved
    pureE: pureE
    spectra: Eseg_best_calc
    trueE: Enull_calc
pipeline_commands_example:
  add_impurity:
    atomtypes: false
    imp_id: 0
    infile: Ag_10nm_reord_relax.lmp
    outfile: Ag_10nm_reord_relax_imp.lmp
  calculate_spectra:
    atomtypes: false
    base_energy: pureE
    gb_file: GBs_best.lst
    infile: Ag_10nm_reord_relax.lmp
    minimize-args:
      potential_type: eam/fs
    minimize_func: minimize_polycrystal
    outfile: Eseg_best_calc
    potential: Ag-Ni.eam.fs
  convert_format:
    infile: Ag_10nm_reord.lmp
    informat: lammps/data
    outfile: Ag_10nm_reord.xyz
    outformat: xyz
  convert_format_atomsk:
    infile: Ag_10nm_reord.lmp
    outfile: Ag_10nm_reord.xyz
  create_monocrystal:
    a: 4.08
    atomtypes: false
    c: 0
    outfile: fcc.xsf
    type: fcc
  create_polycrystal:
    grain_num: 10
    outfile: Ag_10nm.lmp
    stamp_file: fcc.xsf
    x: 100
    y: 100
    z: 100
  extract_pca:
    dispersion_file: false
    infile: soap.lst
    outfile: pca.lst
    pca_num: 10
  get_gb_ids:
    cutoff: 3.5
    infile: Ag_10nm_reord_relax.lmp
    outfile: GBs.lst
  minimize_polycrystal:
    atomtypes:
    - Ag
    energy_file: pureE
    infile: Ag_10nm_reord.lmp
    outfile: Ag_10nm_reord_min.lmp
    potential: Ag-Ni.eam.fs
    potential_type: eam/fs
  minimize_polygpu:
    atomtypes: not used
    energy_file: pureE
    infile: Ag_10nm.lmp
    intype: lammps-data
    minimize_vol: true
    outfile: Ag_10nm_min.xyz
    potential: Unep_v1.txt
    tmp_name: tmp_dir
  predict_lr:
    gb_file: GBs.lst
    infile: pca.lst
    metrics:
    - MAE
    model_file: AgNi-nn.pkl
    outfile: Eseg_pred
  relax_polycrystal:
    atomtypes:
    - Ag
    cool_time: 1e6
    cores: false
    end_temp: 0.1
    heat_time: 1e5
    infile: Ag_10nm_reord.lmp
    init_temp: 0.1
    outfile: Ag_10nm_reord_relax.lmp
    potential: Ag-Ni.eam.fs
    potential_type: eam/fs
    relax_time: 1e6
    start_temp: 700
    stop_temp: 700
  relax_polygpu:
    atomtypes: not used
    cool_time: 100000
    elastic_mod: 76
    end_temp: 0.1
    heat_time: 100000
    infile: dump.xyz
    init_temp: 0.1
    intype: extxyz
    outfile: Ag_10nm_relax.lmp
    potential: Unep_v1.txt
    relax_time: 1000000
    start_temp: 700
    stop_temp: 700
    tmp_name: tmp_dir
  reorder_index:
    infile: Ag_10nm.lmp
    outfile: Ag_10nm_reord.lmp
  replace_and_minimize:
    atomtypes: false
    energy_file: pureE
    imp_id: 0
    infile: Ag_10nm_reord_relax.lmp
    minimize-args:
      potential_type: eam/fs
    minimize_func: minimize_polycrystal
    potential: Ag-Ni.eam.fs
  select_points:
    gb_file: GBs.lst
    infile: pca.lst
    outfile: GBs_best.lst
    points_num: 200
    random_state: 42
  soap:
    atomtypes: false
    cores: false
    infile: Ag_10nm_reord_relax.lmp
    l_max: 12
    n_max: 12
    outfile: soap.lst
    sigma: 1
    soap_cutoff: 6.0
  train_lr:
    gb_file: GBs_best
    metrics:
    - MAE
    outfile: AgNi-nn.pkl
    x_file: pca.lst
    y_file: Eseg_best
pipeline_spectra:
  calculate_spectra:
    atomtypes: Not used, from xyz file
    base_energy: pureE
    gb_file: GBs_best.lst
    infile: ag_10nm_ann_min.xyz
    minimize-args:
      energy_file: E
      intype: extxyz
      outfile: tmp_out.xyz
      tmp_name: tmp_dir
    minimize_func: minimize_polygpu
    outfile: Eseg_best_calc
    potential: Unep_v1.txt
  minimize_polygpu:
    atomtypes: not used
    energy_file: pureE
    infile: ag_10nm_ann_min.xyz
    intype: extxyz
    outfile: tmp_out.xyz
    potential: Unep_v1.txt
    tmp_name: tmp_dir
projname: AgV
specs:
- Ag
- V
